# sms config
PERSONAL_NUMBER: +336XXXXXXXX
SEND_SMS: True
SMS_BODY: "Today was/were born:"

# twilio account info
ACCOUNT_SID: AC91092a4d46d6631c714a1b5a8e971fc7
AUTH_TOKEN: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
TWILIO_NUMBER: +19XXXXXXXXX